/// Flutter icons RdshIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RdshIcons
///      fonts:
///       - asset: fonts/RdshIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RdshIcons {
  RdshIcons._();

  static const _kFontFam = 'RdshIcons';
  static const String? _kFontPkg = null;

  static const IconData achievements = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add2x = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_close = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_document = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_lock = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_question = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friends = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData main = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news_bg = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personal_status_3 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData points = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData projects = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoping_basket = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_1 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_2 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_video = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_check = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_image = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
